// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: balance_user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const changeBalanceUser = `-- name: ChangeBalanceUser :exec
UPDATE users
  SET balance = balance + $2
  WHERE id = $1
`

type ChangeBalanceUserParams struct {
	ID      uuid.UUID `json:"id"`
	Balance int64     `json:"balance"`
}

func (q *Queries) ChangeBalanceUser(ctx context.Context, arg ChangeBalanceUserParams) error {
	_, err := q.db.Exec(ctx, changeBalanceUser, arg.ID, arg.Balance)
	return err
}
