// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: change_hash_user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const changeHashUser = `-- name: ChangeHashUser :exec
UPDATE users
  SET hash = $2
  WHERE id = $1
`

type ChangeHashUserParams struct {
	ID   uuid.UUID `json:"id"`
	Hash string    `json:"hash"`
}

func (q *Queries) ChangeHashUser(ctx context.Context, arg ChangeHashUserParams) error {
	_, err := q.db.Exec(ctx, changeHashUser, arg.ID, arg.Hash)
	return err
}
